# Generated by Django 4.1 on 2022-10-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('slug', models.SlugField()),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('photo', models.URLField(blank=True, verbose_name='Foto')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
            ],
        ),
    ]
