# Generated by Django 4.1 on 2022-10-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_contact_options_alter_contact_speaker_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('start', models.TimeField(null=True, verbose_name='Início')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('speakers', models.ManyToManyField(to='core.speaker', verbose_name='palestrantes')),
            ],
        ),
    ]
